/* AudioPanel.java
 * Created on 24. April 2007, 15:19
 * @author Christian Gruber Bakk.techn.
 */

package ttt.wizard.recorder;

import java.awt.event.ActionListener;

import javax.swing.event.ChangeListener;

/**
 * The audio panel shows the actual microphone recording peak and allows to control the windows microphone recording
 * volume
 */
public class AudioPanel extends javax.swing.JPanel {

    /** Creates new form AudioPanel */
    public AudioPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jSliderRecVolume = new javax.swing.JSlider();
        volumeLabel = new javax.swing.JLabel();
        volumeLevelComponent1 = new ttt.wizard.recorder.VolumeLevelComponent();
        goodLabel = new javax.swing.JLabel();
        perfectLabel = new javax.swing.JLabel();
        highLabel = new javax.swing.JLabel();
        audioSettingsButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        InfoTextArea = new javax.swing.JTextArea();

        setMaximumSize(new java.awt.Dimension(480, 500));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Audio Options"));
        jPanel1.setMaximumSize(new java.awt.Dimension(480, 200));
        jSliderRecVolume.setMaximumSize(new java.awt.Dimension(480, 25));

        volumeLabel.setText("Recording Volume:");

        volumeLevelComponent1.setLayout(new java.awt.GridLayout(1, 0));

        volumeLevelComponent1.setBorder(javax.swing.BorderFactory
                .createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        volumeLevelComponent1.setMaximumSize(new java.awt.Dimension(480, 20));
        goodLabel.setForeground(new java.awt.Color(255, 255, 255));
        goodLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        goodLabel.setText("       good");
        volumeLevelComponent1.add(goodLabel);

        perfectLabel.setForeground(new java.awt.Color(255, 255, 255));
        perfectLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        perfectLabel.setText("perfect");
        volumeLevelComponent1.add(perfectLabel);

        highLabel.setForeground(new java.awt.Color(255, 255, 255));
        highLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        highLabel.setText("too high     ");
        volumeLevelComponent1.add(highLabel);

        audioSettingsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource(
                "/ttt/wizard/recorder/images/Audio.gif")));
        audioSettingsButton.setMaximumSize(new java.awt.Dimension(25, 25));
        audioSettingsButton.setMinimumSize(new java.awt.Dimension(25, 25));
        audioSettingsButton.setPreferredSize(new java.awt.Dimension(25, 25));

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(org.jdesktop.layout.GroupLayout.TRAILING, volumeLevelComponent1,
                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE).add(
                        org.jdesktop.layout.GroupLayout.TRAILING,
                        jPanel1Layout.createSequentialGroup().add(volumeLabel).addPreferredGap(
                                org.jdesktop.layout.LayoutStyle.RELATED, 16, Short.MAX_VALUE).add(jSliderRecVolume,
                                org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 320,
                                org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).addPreferredGap(
                                org.jdesktop.layout.LayoutStyle.RELATED).add(audioSettingsButton,
                                org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25,
                                org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)));
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
                jPanel1Layout.createSequentialGroup().addContainerGap().add(volumeLevelComponent1,
                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35,
                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).add(24, 24, 24).add(
                        jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
                                jSliderRecVolume, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).add(
                                jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false).add(
                                        volumeLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).add(
                                        audioSettingsButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap()));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Info"));
        jPanel2.setMaximumSize(new java.awt.Dimension(480, 300));
        jScrollPane1.setBorder(null);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(480, 100));
        InfoTextArea.setBackground(java.awt.SystemColor.control);
        InfoTextArea.setColumns(20);
        InfoTextArea.setEditable(false);
        InfoTextArea.setFont(new java.awt.Font("Arial Unicode MS", 0, 14));
        InfoTextArea.setLineWrap(true);
        InfoTextArea.setRows(5);
        InfoTextArea.setWrapStyleWord(true);
        InfoTextArea.setBorder(null);
        InfoTextArea.setDoubleBuffered(true);
        jScrollPane1.setViewportView(InfoTextArea);

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1,
                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE));
        jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
                jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(jPanel2,
                org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE).add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
                layout.createSequentialGroup().add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(jPanel1,
                                org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).addContainerGap(113, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Adds a listener to the recording volume slider.
     * 
     * @param listener
     *            listener for the volume slider
     */
    public void addChangeListener(ChangeListener listener) {
        jSliderRecVolume.addChangeListener(listener);
    }

    /**
     * Adds a listener to the Audio Settings Button.
     * 
     * @param actionListener
     *            listener
     */
    public void addActionListener(ActionListener listener) {
        audioSettingsButton.addActionListener(listener);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea InfoTextArea;
    private javax.swing.JButton audioSettingsButton;
    public javax.swing.JLabel goodLabel;
    public javax.swing.JLabel highLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JSlider jSliderRecVolume;
    public javax.swing.JLabel perfectLabel;
    public javax.swing.JLabel volumeLabel;
    public ttt.wizard.recorder.VolumeLevelComponent volumeLevelComponent1;
    // End of variables declaration//GEN-END:variables

}
