/* AfterRecordingPanel.java
 * Created on 29. August 2007, 11:19
 * Christian Gruber Bakk.techn
 */

package ttt.gui.wizard.recorder;

import java.awt.event.ActionListener;


public class AfterRecordingPanel extends javax.swing.JPanel {
    
    private String m_Language;
    
    private String info_DE = "Die Aufnahme wurde erfolgreich abgespeichert. Um " +
            "unter dem gleichen Profil die Aufnahme fortzusetzen, öffnen Sie das " +
            "Menü des Taskicons und klicken Sie auf „Aufnahme Starten“. \n\n" +
            "Ansonsten beenden sie die Aufnahme. Folgende Möglichkeiten stehen " +
            "Ihnen danach zur Verfügung:";
    
    private String info_EN =  "Your recording was successfully saved. To resume recording with " +
            "the same profile and file path click the taskbar icon and select „Start Recording“.\n\n" +
            "Otherwise you have to quit recording. After that you have the possibility to ...";
    
    private String recorder_DE = "Durch erneutes Starten des TTRecorders können Sie eine " +
            "neue Aufnahme unter einem anderen Profil beginnen.";
    
    private String recorder_EN = "... start the TTRecorder anew to begin recording with another " +
            "profile and file path.";
    
    private String player_DE = "Mit Hilfe des TTPlayers können Sie bestehende Aufnahmen " +
            "abspielen.";
    
    private String player_EN = " ... playback existing recordings via the TTPlayer. ";
    
    private String editor_DE = "Um eine vorhandene Aufnahme nachzubearbeiten starten Sie den TTEditor.";
    
    private String editor_EN = "... postprocess an existing recording with the TTEditor.";
    
    private String quitButton_DE = "Aufnahme Beenden";
    
    private String quitButton_EN = "Quit Recording";
    
    private String resumeButton_DE = "Weiter Aufzeichnen";
    
    private String resumeButton_EN = "Resume Recording";
    
    
    public AfterRecordingPanel(String language) {
        initComponents();
        
        m_Language = language;
        
        if(m_Language == "EN"){
            InfoTextArea.setText(info_EN);
            recorderTextArea.setText(recorder_EN);
            playerTextArea.setText(player_EN);
            editorTextArea.setText(editor_EN);
            resumeRecordingButton.setText(resumeButton_EN);
            quitProgramButton.setText(quitButton_EN);
        }else{
            InfoTextArea.setText(info_DE);
            recorderTextArea.setText(recorder_DE);
            playerTextArea.setText(player_DE);
            editorTextArea.setText(editor_DE);
            resumeRecordingButton.setText(resumeButton_DE);
            quitProgramButton.setText(quitButton_DE);
        }
    }
    
    /**
     * Adds listener for quit and resume recording button
     * @param listener
     */
    public void addButtonListener(ActionListener listener){
        quitProgramButton.addActionListener(listener);
        resumeRecordingButton.addActionListener(listener);
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        editorTextArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        recorderTextArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        playerTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        InfoTextArea = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        quitProgramButton = new javax.swing.JButton();
        resumeRecordingButton = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        setMaximumSize(new java.awt.Dimension(550, 480));
        setMinimumSize(new java.awt.Dimension(550, 480));
        setPreferredSize(new java.awt.Dimension(550, 480));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setMaximumSize(new java.awt.Dimension(540, 200));
        jPanel1.setMinimumSize(new java.awt.Dimension(540, 200));
        jPanel1.setPreferredSize(new java.awt.Dimension(540, 200));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jPanel3.setMaximumSize(new java.awt.Dimension(520, 60));
        jPanel3.setMinimumSize(new java.awt.Dimension(520, 60));
        jPanel3.setPreferredSize(new java.awt.Dimension(520, 60));
        editorTextArea.setBackground(java.awt.SystemColor.control);
        editorTextArea.setColumns(20);
        editorTextArea.setEditable(false);
        editorTextArea.setFont(new java.awt.Font("Arial Unicode MS", 0, 14));
        editorTextArea.setLineWrap(true);
        editorTextArea.setRows(5);
        editorTextArea.setWrapStyleWord(true);
        editorTextArea.setMaximumSize(new java.awt.Dimension(450, 40));
        editorTextArea.setMinimumSize(new java.awt.Dimension(450, 40));
        editorTextArea.setPreferredSize(new java.awt.Dimension(450, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel3.add(editorTextArea, gridBagConstraints);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ttt/wizard/recorder/images/Editor_32.gif")));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(9, 15, 9, 9);
        jPanel3.add(jLabel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel1.add(jPanel3, gridBagConstraints);

        jPanel4.setLayout(new java.awt.GridBagLayout());

        jPanel4.setMaximumSize(new java.awt.Dimension(520, 60));
        jPanel4.setMinimumSize(new java.awt.Dimension(520, 60));
        jPanel4.setPreferredSize(new java.awt.Dimension(520, 60));
        recorderTextArea.setBackground(java.awt.SystemColor.control);
        recorderTextArea.setColumns(20);
        recorderTextArea.setEditable(false);
        recorderTextArea.setFont(new java.awt.Font("Arial Unicode MS", 0, 14));
        recorderTextArea.setLineWrap(true);
        recorderTextArea.setRows(5);
        recorderTextArea.setWrapStyleWord(true);
        recorderTextArea.setMaximumSize(new java.awt.Dimension(450, 40));
        recorderTextArea.setMinimumSize(new java.awt.Dimension(450, 40));
        recorderTextArea.setPreferredSize(new java.awt.Dimension(450, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel4.add(recorderTextArea, gridBagConstraints);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ttt/wizard/recorder/images/Recorder_32.gif")));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(9, 15, 9, 9);
        jPanel4.add(jLabel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel1.add(jPanel4, gridBagConstraints);

        jPanel5.setLayout(new java.awt.GridBagLayout());

        jPanel5.setMaximumSize(new java.awt.Dimension(520, 60));
        jPanel5.setMinimumSize(new java.awt.Dimension(520, 60));
        jPanel5.setPreferredSize(new java.awt.Dimension(520, 60));
        playerTextArea.setBackground(java.awt.SystemColor.control);
        playerTextArea.setColumns(20);
        playerTextArea.setEditable(false);
        playerTextArea.setFont(new java.awt.Font("Arial Unicode MS", 0, 14));
        playerTextArea.setLineWrap(true);
        playerTextArea.setRows(5);
        playerTextArea.setWrapStyleWord(true);
        playerTextArea.setMaximumSize(new java.awt.Dimension(450, 40));
        playerTextArea.setMinimumSize(new java.awt.Dimension(450, 40));
        playerTextArea.setPreferredSize(new java.awt.Dimension(450, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel5.add(playerTextArea, gridBagConstraints);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ttt/wizard/recorder/images/Player_32.gif")));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(9, 15, 9, 9);
        jPanel5.add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel1.add(jPanel5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 7, 0);
        add(jPanel1, gridBagConstraints);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Info"));
        jPanel2.setMaximumSize(new java.awt.Dimension(540, 180));
        jPanel2.setMinimumSize(new java.awt.Dimension(540, 180));
        jPanel2.setPreferredSize(new java.awt.Dimension(540, 180));
        jPanel2.setRequestFocusEnabled(false);
        jScrollPane1.setBorder(null);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(510, 145));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(510, 145));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(510, 145));
        InfoTextArea.setBackground(java.awt.SystemColor.control);
        InfoTextArea.setColumns(20);
        InfoTextArea.setEditable(false);
        InfoTextArea.setFont(new java.awt.Font("Arial Unicode MS", 0, 14));
        InfoTextArea.setLineWrap(true);
        InfoTextArea.setRows(5);
        InfoTextArea.setWrapStyleWord(true);
        InfoTextArea.setMaximumSize(new java.awt.Dimension(510, 145));
        InfoTextArea.setMinimumSize(new java.awt.Dimension(510, 145));
        InfoTextArea.setPreferredSize(new java.awt.Dimension(510, 145));
        jScrollPane1.setViewportView(InfoTextArea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 7, 0);
        add(jPanel2, gridBagConstraints);

        jPanel6.setLayout(new java.awt.GridBagLayout());

        quitProgramButton.setText("Aufnahme Beenden");
        quitProgramButton.setActionCommand("Quit");
        quitProgramButton.setMaximumSize(new java.awt.Dimension(150, 30));
        quitProgramButton.setMinimumSize(new java.awt.Dimension(150, 30));
        quitProgramButton.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(12, 14, 12, 14);
        jPanel6.add(quitProgramButton, gridBagConstraints);

        resumeRecordingButton.setText("Weiter Aufzeichnen");
        resumeRecordingButton.setMaximumSize(new java.awt.Dimension(150, 30));
        resumeRecordingButton.setMinimumSize(new java.awt.Dimension(150, 30));
        resumeRecordingButton.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 14, 5, 14);
        jPanel6.add(resumeRecordingButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 7, 0);
        add(jPanel6, gridBagConstraints);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea InfoTextArea;
    private javax.swing.JTextArea editorTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea playerTextArea;
    private javax.swing.JButton quitProgramButton;
    private javax.swing.JTextArea recorderTextArea;
    private javax.swing.JButton resumeRecordingButton;
    // End of variables declaration//GEN-END:variables
    
}
