/* AudioPanel.java
 * Created on 24. April 2007, 15:19
 * @author Christian Gruber Bakk.techn.
 */

package ttt.gui.wizard.recorder;

import java.awt.event.ActionListener;

import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;
import javax.swing.event.ChangeListener;

/**
 * The audio panel shows the actual microphone recording peak and allows to control the windows microphone recording
 * volume
 */
public class AudioPanel extends javax.swing.JPanel {

    /** Creates new form AudioPanel */
    public AudioPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jSliderRecVolume = new javax.swing.JSlider();
        volumeLabel = new javax.swing.JLabel();
        volumeLevelComponent1 = new ttt.gui.wizard.recorder.VolumeLevelComponent();
        goodLabel = new javax.swing.JLabel();
        perfectLabel = new javax.swing.JLabel();
        highLabel = new javax.swing.JLabel();
        audioSettingsButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        InfoTextArea = new javax.swing.JTextArea();

        setMaximumSize(new java.awt.Dimension(480, 500));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Audio Options"));
        jPanel1.setMaximumSize(new java.awt.Dimension(480, 200));
        jSliderRecVolume.setMaximumSize(new java.awt.Dimension(480, 25));

        volumeLabel.setText("Recording Volume:");

        volumeLevelComponent1.setLayout(new java.awt.GridLayout(1, 0));

        volumeLevelComponent1.setBorder(javax.swing.BorderFactory
                .createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        volumeLevelComponent1.setMaximumSize(new java.awt.Dimension(480, 20));
        goodLabel.setForeground(new java.awt.Color(255, 255, 255));
        goodLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        goodLabel.setText("       good");
        volumeLevelComponent1.add(goodLabel);

        perfectLabel.setForeground(new java.awt.Color(255, 255, 255));
        perfectLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        perfectLabel.setText("perfect");
        volumeLevelComponent1.add(perfectLabel);

        highLabel.setForeground(new java.awt.Color(255, 255, 255));
        highLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        highLabel.setText("too high     ");
        volumeLevelComponent1.add(highLabel);

        audioSettingsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource(
                "/ttt/wizard/recorder/images/Audio.gif")));
        audioSettingsButton.setMaximumSize(new java.awt.Dimension(25, 25));
        audioSettingsButton.setMinimumSize(new java.awt.Dimension(25, 25));
        audioSettingsButton.setPreferredSize(new java.awt.Dimension(25, 25));

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(volumeLevelComponent1,GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                .addGroup(GroupLayout.Alignment.TRAILING,jPanel1Layout.createSequentialGroup()
                		.addComponent(volumeLabel)
                		.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                		.addComponent(jSliderRecVolume,GroupLayout.PREFERRED_SIZE, 320,GroupLayout.PREFERRED_SIZE)
                		.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                		.addComponent(audioSettingsButton,GroupLayout.PREFERRED_SIZE, 25,GroupLayout.PREFERRED_SIZE)));
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        				.addContainerGap()
        				.addComponent(volumeLevelComponent1,GroupLayout.PREFERRED_SIZE, 35,GroupLayout.PREFERRED_SIZE)
        				.addGap(24, 24, 24)
        				.addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
        						.addComponent(jSliderRecVolume,GroupLayout.DEFAULT_SIZE,GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
        								.addComponent(volumeLabel, GroupLayout.DEFAULT_SIZE,GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        								.addComponent(audioSettingsButton, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap()));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Info"));
        jPanel2.setMaximumSize(new java.awt.Dimension(480, 300));
        jScrollPane1.setBorder(null);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(480, 100));
        InfoTextArea.setBackground(java.awt.SystemColor.control);
        InfoTextArea.setColumns(20);
        InfoTextArea.setEditable(false);
        InfoTextArea.setFont(new java.awt.Font("Arial Unicode MS", 0, 14));
        InfoTextArea.setLineWrap(true);
        InfoTextArea.setRows(5);
        InfoTextArea.setWrapStyleWord(true);
        InfoTextArea.setBorder(null);
        InfoTextArea.setDoubleBuffered(true);
        jScrollPane1.setViewportView(InfoTextArea);

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1,GroupLayout.Alignment.TRAILING,GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE));
        jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
        		.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE));

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
        		.addComponent(jPanel2,GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,Short.MAX_VALUE)
        		.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE,GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE,GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1,GroupLayout.PREFERRED_SIZE,GroupLayout.DEFAULT_SIZE,GroupLayout.PREFERRED_SIZE).addContainerGap(113, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Adds a listener to the recording volume slider.
     * 
     * @param listener
     *            listener for the volume slider
     */
    public void addChangeListener(ChangeListener listener) {
        jSliderRecVolume.addChangeListener(listener);
    }

    /**
     * Adds a listener to the Audio Settings Button.
     * 
     * @param actionListener
     *            listener
     */
    public void addActionListener(ActionListener listener) {
        audioSettingsButton.addActionListener(listener);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea InfoTextArea;
    private javax.swing.JButton audioSettingsButton;
    public javax.swing.JLabel goodLabel;
    public javax.swing.JLabel highLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JSlider jSliderRecVolume;
    public javax.swing.JLabel perfectLabel;
    public javax.swing.JLabel volumeLabel;
    public ttt.gui.wizard.recorder.VolumeLevelComponent volumeLevelComponent1;
    // End of variables declaration//GEN-END:variables

}
