/* InfoPanel.java
 * Created on 24. Mai 2007, 13:18
 * @author Christian Gruber Bakk.techn.
 */

package ttt.gui.wizard.recorder;

/**
 * Gives the user useful tips for recording a lecture
 */
public class InfoPanel extends javax.swing.JPanel {

    /**
     * Creates new form InfoPanel
     */
    public InfoPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        ScreenResolutionPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ResolutionWarningTextArea = new javax.swing.JTextArea();
        OutputDevicePanel = new javax.swing.JPanel();
        DeviceWarningTextArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(480, 500));
        ScreenResolutionPanel.setLayout(new java.awt.GridBagLayout());

        ScreenResolutionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Screen Resolution"));
        ScreenResolutionPanel.setMaximumSize(new java.awt.Dimension(480, 230));
        ScreenResolutionPanel.setMinimumSize(new java.awt.Dimension(480, 230));
        ScreenResolutionPanel.setPreferredSize(new java.awt.Dimension(480, 230));
        jLabel1
                .setIcon(new javax.swing.ImageIcon(getClass()
                        .getResource("/ttt/wizard/recorder/images/Forbiddance.png")));
        ScreenResolutionPanel.add(jLabel1, new java.awt.GridBagConstraints());

        ResolutionWarningTextArea.setBackground(java.awt.SystemColor.control);
        ResolutionWarningTextArea.setColumns(20);
        ResolutionWarningTextArea.setEditable(false);
        ResolutionWarningTextArea.setFont(new java.awt.Font("Arial Unicode MS", 0, 14));
        ResolutionWarningTextArea.setLineWrap(true);
        ResolutionWarningTextArea.setRows(5);
        ResolutionWarningTextArea.setWrapStyleWord(true);
        ResolutionWarningTextArea.setBorder(null);
        ResolutionWarningTextArea.setDoubleBuffered(true);
        ResolutionWarningTextArea.setMaximumSize(new java.awt.Dimension(200, 150));
        ResolutionWarningTextArea.setMinimumSize(new java.awt.Dimension(200, 150));
        ResolutionWarningTextArea.setPreferredSize(new java.awt.Dimension(200, 150));
        ScreenResolutionPanel.add(ResolutionWarningTextArea, new java.awt.GridBagConstraints());

        OutputDevicePanel.setLayout(new java.awt.GridBagLayout());

        OutputDevicePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Output Device"));
        OutputDevicePanel.setMaximumSize(new java.awt.Dimension(480, 230));
        OutputDevicePanel.setMinimumSize(new java.awt.Dimension(480, 230));
        OutputDevicePanel.setPreferredSize(new java.awt.Dimension(480, 230));
        DeviceWarningTextArea.setBackground(java.awt.SystemColor.control);
        DeviceWarningTextArea.setColumns(20);
        DeviceWarningTextArea.setEditable(false);
        DeviceWarningTextArea.setFont(new java.awt.Font("Arial Unicode MS", 0, 14));
        DeviceWarningTextArea.setLineWrap(true);
        DeviceWarningTextArea.setRows(5);
        DeviceWarningTextArea.setWrapStyleWord(true);
        DeviceWarningTextArea.setBorder(null);
        DeviceWarningTextArea.setDoubleBuffered(true);
        DeviceWarningTextArea.setMaximumSize(new java.awt.Dimension(200, 150));
        DeviceWarningTextArea.setMinimumSize(new java.awt.Dimension(200, 150));
        DeviceWarningTextArea.setPreferredSize(new java.awt.Dimension(200, 150));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        OutputDevicePanel.add(DeviceWarningTextArea, gridBagConstraints);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ttt/wizard/recorder/images/Device.png")));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        OutputDevicePanel.add(jLabel2, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                layout.createSequentialGroup().addGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
                                ScreenResolutionPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(OutputDevicePanel,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)).addGap(20, 20, 20)));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                layout.createSequentialGroup().addComponent(ScreenResolutionPanel,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(
                                OutputDevicePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE).addGap(
                                83, 83, 83)));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea DeviceWarningTextArea;
    public javax.swing.JPanel OutputDevicePanel;
    public javax.swing.JTextArea ResolutionWarningTextArea;
    public javax.swing.JPanel ScreenResolutionPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
