/* OptionPanel.java
 * Created on 17. April 2007, 13:20
 * @author Christian Gruber BAkk.techn.
 */

package ttt.gui.wizard.recorder;

import java.awt.event.ActionListener;
import java.awt.event.ItemListener;
import java.util.prefs.Preferences;

import javax.swing.GroupLayout;
import javax.swing.JComboBox;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;

import ttt.record.LectureProfile;

/**
 * With the option panel users can create and manage their profiles
 */
public class OptionPanel extends javax.swing.JPanel {
    
    static Preferences userPrefs = Preferences.userRoot().node("/TTT");
    
    /**
     * Creates new form OptionPanel
     */
    public OptionPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabelLecture = new javax.swing.JLabel();
        jLabelTeacher = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelFilename = new javax.swing.JLabel();
        jLabelFilenameField = new javax.swing.JLabel();
        jLabelTitlefiled = new javax.swing.JLabel();
        jComboBoxTeacher = new JComboBox(LectureProfile.getTeachers());
        jComboBoxLecture = new JComboBox(LectureProfile.getLectures());
        jLabelRecordingPath = new javax.swing.JLabel();
        jLabelRecordingPathField = new javax.swing.JLabel();
        jButtonFileChooser = new javax.swing.JButton();
        jButtonDeleteProfiles = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        InfoTextArea = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jCheckBoxVideo = new javax.swing.JCheckBox();

        setMaximumSize(new java.awt.Dimension(480, 520));
        setMinimumSize(new java.awt.Dimension(480, 520));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Profiles"));
        jPanel1.setMaximumSize(new java.awt.Dimension(480, 200));
        jPanel1.setPreferredSize(new java.awt.Dimension(480, 200));
        jLabelLecture.setText("Lecture:");

        jLabelTeacher.setText("Teacher:");

        jLabelTitle.setText("Title:");

        jLabelFilename.setText("Filename:");

        jComboBoxTeacher.setEditable(true);
        jComboBoxTeacher.setActionCommand("comboBoxChangedTeacher");
        jComboBoxTeacher.setMaximumSize(new java.awt.Dimension(309, 18));
        jComboBoxTeacher.setPreferredSize(new java.awt.Dimension(309, 18));

        jComboBoxLecture.setEditable(true);
        jComboBoxLecture.setActionCommand("comboBoxChangedLecture");
        jComboBoxLecture.setMaximumSize(new java.awt.Dimension(309, 18));
        jComboBoxLecture.setPreferredSize(new java.awt.Dimension(309, 18));

        jLabelRecordingPath.setText("Recording Path:");

        jLabelRecordingPathField.setText(userPrefs.get("record_path", "."));

        jButtonFileChooser.setText("jButton1");
        jButtonFileChooser.setActionCommand("jButtonFileChooser");
        jButtonFileChooser.setMaximumSize(new java.awt.Dimension(25, 25));
        jButtonFileChooser.setMinimumSize(new java.awt.Dimension(25, 25));
        jButtonFileChooser.setPreferredSize(new java.awt.Dimension(25, 25));

        jButtonDeleteProfiles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ttt/wizard/recorder/images/Delete.gif")));
        jButtonDeleteProfiles.setActionCommand("deleteProfiles");
        jButtonDeleteProfiles.setMaximumSize(new java.awt.Dimension(25, 25));
        jButtonDeleteProfiles.setMinimumSize(new java.awt.Dimension(25, 25));
        jButtonDeleteProfiles.setPreferredSize(new java.awt.Dimension(25, 25));

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelLecture, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTeacher, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTitle, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelRecordingPath, GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                    .addComponent(jLabelFilename, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelFilenameField, GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(jLabelTitlefiled, GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addGroup(GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelRecordingPathField, GroupLayout.PREFERRED_SIZE, 260, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(jButtonFileChooser, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBoxTeacher, GroupLayout.Alignment.LEADING, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxLecture, GroupLayout.Alignment.LEADING, 0, 327, Short.MAX_VALUE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)))
                .addGap(58, 58, 58))
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(430, Short.MAX_VALUE)
                .addComponent(jButtonDeleteProfiles, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButtonDeleteProfiles, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLecture)
                    .addComponent(jComboBoxLecture, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTeacher)
                    .addComponent(jComboBoxTeacher, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitlefiled, GroupLayout.PREFERRED_SIZE, 17, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTitle))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFilenameField, GroupLayout.PREFERRED_SIZE, 18, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFilename))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRecordingPathField)
                    .addComponent(jButtonFileChooser, GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jLabelRecordingPath))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(SwingConstants.VERTICAL,jComboBoxLecture, jComboBoxTeacher, jLabelFilename, jLabelFilenameField, jLabelLecture, jLabelRecordingPath, jLabelRecordingPathField, jLabelTeacher, jLabelTitle, jLabelTitlefiled);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Info"));
        jPanel2.setAutoscrolls(true);
        jPanel2.setMaximumSize(new java.awt.Dimension(480, 200));
        jPanel2.setPreferredSize(new java.awt.Dimension(480, 200));
        jScrollPane2.setBorder(null);
        InfoTextArea.setBackground(java.awt.SystemColor.control);
        InfoTextArea.setColumns(20);
        InfoTextArea.setFont(new java.awt.Font("Arial Unicode MS", 0, 14));
        InfoTextArea.setLineWrap(true);
        InfoTextArea.setRows(5);
        InfoTextArea.setText("\n");
        InfoTextArea.setWrapStyleWord(true);
        InfoTextArea.setAutoscrolls(false);
        InfoTextArea.setBorder(null);
        InfoTextArea.setMaximumSize(new java.awt.Dimension(470, 200));
        jScrollPane2.setViewportView(InfoTextArea);

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Video Selection"));
        jPanel3.setMaximumSize(new java.awt.Dimension(480, 70));
        jPanel3.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(480, 70));
        jPanel3.setVerifyInputWhenFocusTarget(false);
        jCheckBoxVideo.setText("incl. Video");
        jCheckBoxVideo.setActionCommand("jCheckBoxVideo");
        jCheckBoxVideo.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBoxVideo.setMargin(new java.awt.Insets(0, 0, 0, 0));

        GroupLayout jPanel3Layout = new GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jCheckBoxVideo)
                .addContainerGap(378, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxVideo)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                        .addComponent( jPanel1, GroupLayout.Alignment.LEADING, 0, 480, Short.MAX_VALUE)
                        .addComponent( jPanel2, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
            
    
    /**
     * Adds listeners to the different buttons of the option panel
     * @param listener listener for the option buttons
     */
    public void addActionListener(ActionListener listener) {
        jComboBoxTeacher.addActionListener(listener);
        jComboBoxLecture.addActionListener(listener);
        jButtonFileChooser.addActionListener(listener);
        jButtonDeleteProfiles.addActionListener(listener);
        //jButtonImportProfiles.addActionListener(listener);
        //jButtonExportProfiles.addActionListener(listener);
    }
    
    /**
     * Adds a listener to the video checkbox
     * @param listener listener which will be informed if the video checkbox has changed
     */
    public void addItemChangedListener(ItemListener listener) {
        jCheckBoxVideo.addItemListener(listener);
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea InfoTextArea;
    public javax.swing.JButton jButtonDeleteProfiles;
    private javax.swing.JButton jButtonFileChooser;
    public javax.swing.JCheckBox jCheckBoxVideo;
    public javax.swing.JComboBox jComboBoxLecture;
    public javax.swing.JComboBox jComboBoxTeacher;
    public javax.swing.JLabel jLabelFilename;
    public javax.swing.JLabel jLabelFilenameField;
    public javax.swing.JLabel jLabelLecture;
    public javax.swing.JLabel jLabelRecordingPath;
    public javax.swing.JLabel jLabelRecordingPathField;
    public javax.swing.JLabel jLabelTeacher;
    public javax.swing.JLabel jLabelTitle;
    public javax.swing.JLabel jLabelTitlefiled;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
    
}
